### ISSUE TITLE
KeyError: 'history'

### ISSUE THREAD

**Issue by LiohMoeller** [hcguersoy/cleanreg#13]
I am running `docker run --rm -it hcguersoy/cleanreg:v0.7.0 -r https://myregistry -cf -k 5 -i` and get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/cleanreg.py", line 534, in get_tags_dates_digests_byrepo
    pool.map(funcpart, tags_all)
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
KeyError: 'history'

Traceback (most recent call last):
  File "/cleanreg.py", line 678, in <module>
    args.md_workers, args.cacert)
  File "/cleanreg.py", line 583, in get_all_tags_dates_digests
    result[repo] = repos_tags_digest[repo]
  File "<string>", line 2, in __getitem__
  File "/usr/local/lib/python2.7/multiprocessing/managers.py", line 774, in _callmethod
    raise convert_to_error(kind, result)
KeyError: u'library/postgres'

```

**Comment by kekru** [comment]
Hi, I think, this is the relevant code

```python
metadata_request = regserver + repo + "//manifests/" + tag
metadata_header = {'Accept': 'application/vnd.docker.distribution.manifest.v1+json'}
metadata = requests.get(metadata_request, headers=metadata_header, verify=cacert,
                            auth=get_auth()).json()

creation_date = json.loads(metadata['history'][0]['v1Compatibility'])['created']
```

GET Request to `https://myregistry/library/postgres//manifests/<your docker tag>`  
With request header `Accept=application/vnd.docker.distribution.manifest.v1+json` should return a json with a `history` field.  
Does it or not?

If your registry is password protected, you need to pass credentials using `-u` and `-pw`

**Comment by hcguersoy** [comment]
Closing this as obviously solved.

**Comment by syunhan** [comment]
harbor only support docker v2 api
so if you use harbor registry, you could not use this

**Comment by hcguersoy** [comment]
Hello @syunhan 
a registry v2 API should accept/support media type `application/vnd.docker.distribution.manifest.v1+json` as specified in the [image manifest specification v2](https://docs.docker.com/registry/spec/manifest-v2-2/). As always, this may depend finally on the implementation.

Can you please check if harbor registry returns a result for media type _fat manifest_, e.g. with:

```shell
httpie --verbose get http://localhost:5000/v2/abc/manifests/5 'Accept:application/vnd.docker.distribution.manifest.list.v2+json'
```
