### ISSUE TITLE
Rename --quiet/-q option to --assume-yes or --yes/-y

### ISSUE THREAD

**Issue by derwebcoder** [hcguersoy/cleanreg#4]
I think it would be more obvious to rename the --quiet option to --assume-yes like in "apt" or other similar tools.
In the end --quiet does not even reduce the logs but just assume yes for the user interaction.

**Comment by derwebcoder** [comment]
I re added quiet-option for backwards compatibility.

**Comment by hcguersoy** [comment]
Merged the PR, closing this issue.
