### ISSUE TITLE
runAllTests.sh is not working

### ISSUE THREAD

**Issue by derwebcoder** [hcguersoy/cleanreg#5]
See attached log file.

I assume the cause is the following:

```
Create images for registry and cleanreg
Using Docker Registry in version 2.5.1. You can define the version by setting the REGISTRYTAG env variable
Sending build context to Docker daemon  3.072kB
Step 1/3 : ARG TAG
Please provide a source image with `from` prior to commit
Sending build context to Docker daemon  3.072kB
Step 1/4 : ARG BASEIMAGE
Please provide a source image with `from` prior to commit
Sending build context to Docker daemon  235.5kB
```

I have installed docker-ce 17.03.1~ce-0~ubuntu-xenial

[runAllTests.txt](https://github.com/hcguersoy/cleanreg/files/1096011/runAllTests.txt)

**Comment by kekru** [comment]
I think it's only running on a newer docker version.

The tests run docker registries in different versions. For that the docker hub tag is set as an build-arg variable in the Dockerfile (see [here](https://github.com/hcguersoy/cleanreg/tree/master/test/config/docker-registry)).

The feature to define a "--build-arg" variable in the FROM statement was merged in docker's master branch on Apr 10th (see [here](https://github.com/moby/moby/pull/31352)).

So it should work in Docker CE 17.05, maybe 17.04 :)

**Comment by hcguersoy** [comment]
Can we close this?

**Comment by derwebcoder** [comment]
Yes. But should this information at least be added to the "Run tests" part of the README.md? Not everybody has migrated to the newest version yet.

**Comment by hcguersoy** [comment]
IMHO this is documented now and we can close this.
