### ISSUE TITLE
Deleting wrong images if tagged more than once

### ISSUE THREAD

**Issue by derwebcoder** [hcguersoy/cleanreg#8]
cleanreg deletes images which are tagged twice, even if setting --ignore option. Looks like --ignore is only checking for duplicates in the same repository.

Having an image `example-a:test-123` and tagging it additionally `example-b:test-123`. Both will have the same digest. Running cleanreg for `example-b` and deleting the image, it will also delete `example-a`, even if --ignore option has been set.

**Comment by hcguersoy** [comment]
There is some discussions about this in the docker distribution project, somehow a bit unstrucutured. see https://github.com/docker/distribution/issues/2170

**Comment by hcguersoy** [comment]
Should be fixed with the commit above. Please check version 0.5.0 if it is OK now. I've added some new tests too, to be sure that we cover this but just wondering why the tests before run successfully.
